# Generated by Django 3.2.6 on 2021-10-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_direction',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
