# Generated by Django 3.2.6 on 2021-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_alter_link_link_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='issued_at',
            field=models.TimeField(),
        ),
    ]
