# Generated by Django 3.2.6 on 2021-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_alter_link_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='expiring_link',
            field=models.URLField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
