# Generated by Django 3.2.6 on 2021-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_alter_img_expiring_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='expiring_link',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
